workspace(name = "logs_flags")

load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

http_archive(
    name = "com_github_gflags_gflags",
    urls = ["https://github.com/gflags/gflags/archive/master.tar.gz"],
    strip_prefix = "gflags-master",
)

http_archive(
    name = "com_github_glog_glog",
    urls = ["https://github.com/google/glog/archive/master.tar.gz"],
    strip_prefix = "glog-master",
)